[8acfd77f-b2e6-4cf0-a3c2-4fbbb0dc6a8a] # you can use a UUID generator for this. The value inside the brackets acts as a API key for the child
    type = api
    enabled = yes
    default history = 3600
    default memory mode = dbengine
    health enabled by default = auto
    allow from = *
